import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, ScrollView, SafeAreaView } from 'react-native';
import { buildDaySchedule } from '@jee/planner-engine';
import type { ScheduleBlock } from '@jee/shared-types';
import { SAMPLE_TASKS, getSampleFixedEvents } from './lib/sampleData';

function formatTime(iso: string): string {
  const d = new Date(iso);
  return d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function BlockRow({ block }: { block: ScheduleBlock }) {
  const isFixed = block.type === 'fixed_event';
  return (
    <View style={[styles.block, isFixed && styles.blockFixed]}>
      <Text style={styles.blockTime}>
        {formatTime(block.startTime)} – {formatTime(block.endTime)}
      </Text>
      <Text style={styles.blockLabel}>{block.label}</Text>
      <Text style={styles.blockType}>{block.type}</Text>
    </View>
  );
}

export default function App() {
  const today = new Date();
  const dateStr = today.toISOString().slice(0, 10);

  const schedule = buildDaySchedule({
    date: dateStr,
    fixedEvents: getSampleFixedEvents(today),
    dayStart: `${dateStr}T06:30:00`,
    dayEnd: `${dateStr}T22:00:00`,
    minBreakMinutes: 10,
    tasks: [...SAMPLE_TASKS].sort((a, b) => b.priorityScore - a.priorityScore),
  });

  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView style={styles.container}>
        <Text style={styles.heading}>Today's Plan</Text>
        <Text style={styles.subheading}>{dateStr} — generated by planner-engine</Text>
        {schedule.blocks.map((block) => (
          <BlockRow key={block.id} block={block} />
        ))}
      </ScrollView>
      <StatusBar style="auto" />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#fff' },
  container: { flex: 1, paddingHorizontal: 16 },
  heading: { fontSize: 26, fontWeight: '700', marginTop: 16 },
  subheading: { fontSize: 13, color: '#666', marginBottom: 16 },
  block: { borderWidth: 1, borderColor: '#e2e2e2', borderRadius: 10, padding: 12, marginBottom: 10 },
  blockFixed: { backgroundColor: '#f3f3f3', borderColor: '#ccc' },
  blockTime: { fontSize: 12, color: '#888' },
  blockLabel: { fontSize: 16, fontWeight: '600', marginTop: 2 },
  blockType: { fontSize: 12, color: '#999', marginTop: 2, textTransform: 'uppercase' },
});